apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorial-dep
  labels:
    app: factorial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: factorial
  template:
    metadata:
      labels:
        app: factorial
    spec:
      containers:
        - name: factorial
          image: eblee73/factorial:0.0.3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]

          startupProbe:
            httpGet:
              path: /probe/startup
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 1
            failureThreshold: 10

          readinessProbe:
            httpGet:
              path: /probe/ready
              port: 8080
            periodSeconds: 1
            successThreshold: 2
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /probe/live
              port: 8080
            periodSeconds: 1
            failureThreshold: 15
