apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorial-dep
  labels:
    app: factorial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: factorial
  template:
    metadata:
      labels:
        app: factorial
    spec:
      containers:
        - name: factorial
          terminationGracePeriodSeconds: 60
          image: eblee73/factorial:0.0.3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]

          startupProbe:
            httpGet:
              path: /probe/startup
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /probe/ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3

          livenessProbe:
            httpGet:
              path: /probe/live
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3